### ISSUE TITLE
TODO (final, seriously...) 

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#75]
- [x] Fine tune composition mode 
- [x] Sequencer randomization
- [x] USB parsing of non-Manta HID devices
     - [x] implement "learn" for joysticks
     - [x] figure out why tether isn't sensed
     - [x] check nintendo controller
     - [x] test on PS2 controller and get it working properly
     - [x] HID keyboard 10-key 
- [x] Preset Storage functionality
     - [x] hook it up with the button input on the module
     - [x] make decisions about MIDI and keyboard mode presets
- [x] Fix Windows USB-device problem
- [x] MIDI learn 
          - keyboard [cc: 0-127], joystick [0-xxxx]
          - SAVE 
          - specific jack-by-jack, jacks have default CC number, high-byte pair
- [x] Extra modes: all cc midi, all trigger, combined cc/trigger (midi learn will account for others)
- [x] TUNING 
     - [x] send Scala format serialized from computer
     - [x] parse serialized Scala format in MantaMate
- [x] Computer. All modes same. But high resolution DAC output control.
- [x] external trigger/gate or touch as trigger/gate --- this should be a single variable that enables ARPEGGIATOR VS KEYBOARD in keyboard mode and SEQUENCER VS ARBITRARY KEYBOARD when in sequencer mode. 
                * Add "arpeggiator" mode for keyboard, computer, and keyboard/manta. For MIDI devices, it can be accessed by selecting preset 00, for Manta, it can be accessed by selecting an option in the bottom left function button menu
               *  Add "keyboard-style" sequencer option where it will ignore gate inputs and instead clock when a hexagon is pressed, so you can play it like a keyboard  (this should be combined with the above, just a simple "gateOrTouch" variable that is set by default to gate in sequencer mode and touch in keyboard mode, but can be switched to the other value in either mode)
- [x] Pitch bend? (on/off, +- 2 semitones)
- [x] Maybe jump to step (bottom right function button), relocate interaction modes 
- [x] Decide on P button preferences (Preference selections saved and loaded for next boot)
          - Tunings
          - Global Portamento
          - External or *Internal* Clock (+ BPM)
          - Maybe internal clock division (1/4note, 1/16note) accessed by pushing "save" while in 
Clock preferences menu
- [x] Keyboard slider functionality --- pitch bend?
          - Slider Mode 1:  CV1/2; Slider Mode 2: PitchBend/Glide (slider mode 2 active while "mode options" button is held down); 
- [x] add functionality for when no device is plugged in -- still produce clock, maybe with randomness option, and have noise-sample-and-hold
- [x] Firmware updatability 
- [x] Bug cleanse

**Comment by mulshine** [comment]
Think we got all these :) 

lots of squash.
